### ISSUE TITLE
The database is not generated

### ISSUE THREAD

**Issue by DTHerrera** [danisaleem/Flask_App#1]
Hi, Dani.

Let me congratulate you, Microblog is a great job you've done. When I want to use it, it generates the following error:

File "c:\program files\python37\lib\site-packages\sqlalchemy\engine\default.py", line 581, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: user
[SQL: SELECT user.id AS user_id, user.username AS user_username, user.email AS user_email, user.password_hash AS user_password_hash, user.about_me AS user_about_me, user.last_seen AS user_last_seen
FROM user
WHERE user.username = ?
 LIMIT ? OFFSET ?]
[parameters: ('admin', 1, 0)]
(Background on this error at: http://sqlalche.me/e/e3q8)

What actions do I have to do to get the database to be generated correctly?

Thank you very much for the support

Greetings.
Domingo Tapia

**Comment by danisaleem** [comment]
Hello DTHerrera, 

Thank you for your message.
quick fix, you can use the below migration script to generate the tables. 

`flask db migrate -m "Initial migration."`
`flask db upgrade`

Let me know if this gets the app running and if you have any further questions.

Thanks & Regards,
Dani
